### ISSUE TITLE
Main.py 40: no fast renderer available

### ISSUE THREAD

**Issue by ohcomeonman** [Fernando-Medeiros/Pygame-RPG#1]
sorry, I'm quite new to github and coding, but when I follow the steps and finally reach to running main.py, this issue accured:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/129945411/230538421-31516d4f-cdad-4ede-8363-add4d07bf8fd.png">
sorry if this is a stupid question, but I appreciate if anyone answers!

**Comment by Fernando-Medeiros** [comment]
hey @ohcomeonman  O\

I did a test now installing the project from the beginning, and this alert did not appear.

It could be the lack of some dependencies for the operating system, I use Linux Ubuntu and a few months ago when running pygame, I needed to install modules necessary to render the SDL.

Were you able to run the game?

**Comment by ohcomeonman** [comment]
I'm not able to run the game, I first thought it would be kind of internet error or something...
I'm using replit and I use the pygame module.

**Comment by Fernando-Medeiros** [comment]
I managed to run the game in the replit.

The replit has a default template with the pygame configuration, I took this template and uploaded it from the game repository.
There are some problems running the project there, for example memory consumption, cpu and screen size, but it works.

The project is on my profile.
[link](https://replit.com/@FernandoMedeir8)

**Comment by ohcomeonman** [comment]
hello, do you change anything? if yes, can you show where you changed it?

**Comment by Fernando-Medeiros** [comment]
First I did a test by importing the project directly from github, but the game didn't run, it showed an **error for not finding a video driver.**

After the fastest way, O_o, I got the ready-made pygame template available in the replit, and I imported the project files straight from my machine.

The problem was the build needed to recognize the video and audio drivers on the replit platform.

Any pygame project you can do there needs to have the same pygame build, which is in the pyproject.toml and poetry files. lock

- [poetry.lock](https://replit.com/@FernandoMedeir8/The-Hero-Journey#poetry.lock)
- [pyproject.toml](https://replit.com/@FernandoMedeir8/The-Hero-Journey#pyproject.toml)

```sh
# the default build of pygame in replit already includes the libs

~/The-Hero-Journey$ pip list
Package            Version
------------------ -----------
cachecontrol       0.12.11
cachy              0.3.0
certifi            2022.12.7
cffi               1.15.1
charset-normalizer 3.0.1
cleo               0.8.1
clikit             0.6.2
crashtest          0.3.1
cryptography       39.0.0
dearpygui          1.6.2
debugpy            1.6.3
distlib            0.3.6
filelock           3.9.0
html5lib           1.1
idna               3.4
jedi               0.18.1
jeepney            0.8.0
keyring            21.8.0
lockfile           0.12.2
msgpack            1.0.4
packaging          21.3
parso              0.8.3
pastel             0.2.1
pexpect            4.8.0
pip                21.2.3
pkginfo            1.9.6
platformdirs       2.6.2
pluggy             1.0.0
poetry             1.1.11
poetry-core        1.0.8
ptyprocess         0.7.0
pycparser          2.21
pyflakes           2.4.0
pygame             2.1.2
pylev              1.4.0
pyparsing          3.0.9
python-lsp-jsonrpc 1.0.0
python-lsp-server  1.5.0
pytoolconfig       1.2.2
requests           2.28.2
requests-toolbelt  0.9.1
rope               1.3.0
secretstorage      3.3.3
setuptools         57.4.0
shellingham        1.5.0.post1
six                1.16.0
toml               0.10.2
tomli              2.0.1
tomlkit            0.11.6
ujson              5.4.0
urllib3            1.26.14
virtualenv         20.17.1
webencodings       0.5.1
whatthepatch       1.0.2
yapf               0.32.0
```

**Comment by ohcomeonman** [comment]
I think the way to solve the problem with no video driver is that you can use a dummy driver:
import os
os.environ["SDL_VIDEODRIVER"] = "dummy"
I also used the pygame template.

**Comment by ohcomeonman** [comment]
thank you for your help, I now fix this issue and I start the game perfectly, but the only problem is that the scrren didn't shows all the game, but that's nt your problem, so I appreciate all your help!
